#version: "{build}"
# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2015

platform:
#- x64
- x86

shallow_clone: true

environment:
  matrix:
    - BUILD_TYPE: Debug
      MINGW_PATH: C:\MinGW  # see https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin
      TOOLCHAIN: MinGW

    - BUILD_TYPE: nmake

install:
  - if "%TOOLCHAIN%"=="MinGW" set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%TOOLCHAIN%"=="MinGW" set PATH=%MINGW_PATH%\bin;%PATH%

build_script:
  - echo build_script
  #- if "%TOOLCHAIN%"=="MinGW" ( mingw32-make -f Makefile.mingw all ) # TODO
  - if "%TOOLCHAIN%"=="MinGW" ( mingw32-make -f Makefile.mingw gk-slo.exe gk-shp.exe )

  # Use Visual studio 2013 toolchain - see https://www.appveyor.com/docs/build-environment/#visual-studio-2013 and https://msdn.microsoft.com/en-us/library/f2ccy3wt(v=vs.120).aspx :
  - if "%BUILD_TYPE%" == "nmake" if "%platform%" == "x86" ( call  "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86 )
  # - if "%BUILD_TYPE%" == "nmake" ( nmake /f Makefile.msc all ) # TODO
  - if "%BUILD_TYPE%" == "nmake" ( nmake /f Makefile.msc gk-slo.exe gk-shp.exe )

test_script:
  - echo test_script
  - if "%TOOLCHAIN%"=="MinGW" ( mingw32-make -f Makefile.mingw test )
  - if "%BUILD_TYPE%" == "nmake" ( nmake /f Makefile.msc test )

deploy: off
