#version: "{build}"

#branches:
#  only:
#    - master

shallow_clone: true

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image:
  # https://www.appveyor.com/docs/windows-images-software/#visual-studio-2015
  - Visual Studio 2015

platform:
  - x86
  #- x64

configuration:
  - Release

environment:
  matrix:
    - BUILD_TYPE: Debug
      TOOLCHAIN: MSYS2
      TOOLPATH: C:\msys64\win32;C:\msys64\mingw32\bin;C:\msys64\usr\bin

    - BUILD_TYPE: Debug
      TOOLCHAIN: MSC

#init:
#  # CMake refuses to generate MinGW Makefiles if sh.exe is in the Path
#  - ps: Get-Command sh.exe -All | Remove-Item

#before_build:

install:
  - if "%TOOLCHAIN%"=="MSYS2" set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%TOOLCHAIN%"=="MSYS2" set PATH=%TOOLPATH%;%PATH%

  - if "%TOOLCHAIN%"=="MSC" call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%

build_script:
  #- if "%TOOLCHAIN%"=="MSYS2" ( mingw32-make -f Makefile.mingw all ) # TODO
  - if "%TOOLCHAIN%"=="MSYS2" ( mingw32-make -f Makefile.mingw gk-slo.exe gk-shp.exe )

  #- if "%TOOLCHAIN%"=="MSC" ( nmake /f Makefile.msc all ) # TODO
  - if "%TOOLCHAIN%"=="MSC" ( nmake /f Makefile.msc gk-slo.exe gk-shp.exe )

#after_build:

#artifacts:
#  - path:
#    name:

test_script:
  - if "%TOOLCHAIN%"=="MSYS2" ( mingw32-make -f Makefile.mingw test )

  - if "%TOOLCHAIN%" == "MSC" ( nmake /f Makefile.msc test )

#on_success:

#on_finish:

deploy: off
